### ISSUE TITLE
Can't get it to work for the iOS 7/8/9 simulators w/ iPhone 4S 

### ISSUE THREAD

**Issue by cravemaster** [CoBrA2168/AdvancedSettings8#1]

**Comment by joshuaseltzer** [comment]
Are you using simject?  You probably have to change some things in the makefile to get it working.
https://github.com/angelXwind/simject

There's also a chance that the internal settings aren't available on the simulator.

**Comment by cravemaster** [comment]
I did work it out w/ simject, yes, but that was only for iOS 10.3 simulator (and I took screenshots of all the changes that were made by Apple in those settings for things like a new submenu called Misc System Animations, some new/removed settings for Control Center, Lock Screen, App Switcher, etc. And in fact, I decided they were kind of valuable and very rare, so I decided it was all the worth for sharing to the world, so I put they are on my GitHub profile, and they are currently still there as we speak).

Sadly, no I could not however get them to be accessed on the iOS 7, 8, or 9 simulators even w/ the simulator model set to a device like iPhone 4S, iPhone 5, or iPads like iPad mini or whatever. I just honestly decided to give up and go about my day (but was still slightly infuriated at this result >:/).

**Comment by joshuaseltzer** [comment]
Hmm, that's quite odd.  I actually never tried using AdvancedSettings8 with the simulator / simject, so that's good to know that it's at least working on the latest simulators.

I don't really provide support for running on the simulator, so I can't really confirm how to fix compatibility with those devices.

**Comment by cravemaster** [comment]
When iOS 11 comes out then I'll get access to them again too, even for Maps and Photos internal settings if they are still there in the Summer of this year :P.

I even went to get the Maps and Photos internal settings as well ("DebugPanelEnabled" to "com.apple.Maps.plist" and "PUEnableDoubleTapSettings" to "com.apple.mobileslideshow.plist"), and they both require an internal install, and accessing the Maps one means going to the Maps and tapping the status bar and the menu comes up, and for Photos you do the same but double-tap the status bar to access. My InternalSettings10 project even has options to enable these.

Fun fact about iOS Maps' internal settings: users complained about that not being able to access. Well if they'd take their heads out of their ass they'd see Apple put a check that said you need an internal install as of iOS 8.3, and @hamzasood didn't even say that, so I had to investigate which made things for him to say impossible on his social network sites.

Anyway I'm off my tire swing so now I'll be able to go back to drinking chocolate milk and investigate more of why the internal settings cannot seem to load on the iOS Simulator as of iOS 7, or 8, or 9.

Tbh, I'd like also to get the iOS 7.0 beta 1 internal settings; which I *DID NOT* manage to successfully running on to the iOS Simulator either, nor any device except for my iPhone 4 GSM.
However, on the iPhone 4 - which was almost equally as challenging as getting them on the iOS Simulator - I *DID* actually manage to successfully get them running on iPhone 4 running 7.0 beta 2; just sadly not iOS 7.0 beta 1 (because AFAIK that ACTUALLY REQUIRES a more specific framework, which is the PrototypeTools.framework - which is only available in Xcode 5, or maybe in the iOS 7.0 beta 2 DYLD cache - as the iOS 7.0 beta 1 does not have that in the DYLD cache whatsoever like iOS 7.0 beta 2 does, you see), and had I known how to use a DYLD binary disposer/exporter (or something like that), I could have just dumped/exported or whatever the PrototypeTools.framework and put it in the appropriate folder location in the iOS 7 beta filesystem in iFunBox or something *if* rooted on the iPhone 4.

And so sadly, the thing about this particular sentiment/statement is: unless you have an iPhone 4 running a tethered downgrade of sund0wn of the iOS 7.0 beta 2 IPSW/firmware and you use a hack like the SSH RAMDisk jar, then you could just deal w/ it from there simply by putting that in the appropriate folder location.


But, see, but here's the thing, see, I've dealt with this whole.. internal settings stuff ever since @hamzasood tweeted them in June 2013 and have always loved them, and wanted to share my knowledge of them wherein Hamza won't (which he and I have Aspergers which is similar to Autism :P). The whole thing has been very fun and I've new things from these settings, especially the Maps internal settings as well as the Photos internal settings along the side, and I just love poking in these from time to time, and refuse to (and simply just won't) walk away from doing this sort of thing.

I've even made a video of it running iOS 7.0 beta 2, sadly 3/4 years later which is on this link to YouTube. https://www.youtube.com/watch?v=nQwlpihAy-E

**Comment by joshuaseltzer** [comment]
Oh that's some awesome information!  I never really looked into it that much, other than having the ability to change some of those settings back with iOS8.  I never even tried to get them on the simulator.

Hopefully they remain with iOS11 like you said.

**Comment by cravemaster** [comment]
(Sorry for my late response by the way) Maybe over the summer when iOS 11 comes and Xcode 9 is out I will get the opportunity to see if it is there, thanks 😄👍🏻🤛🏻

**Comment by joshuaseltzer** [comment]
Hopefully!
